import { ActivatedRoute, Router } from '@angular/router';
import { HeadService } from './head.service';
import { Observable } from 'rxjs/Observable';
import 'rxjs';
import { MetaLoader } from './meta.loader';
export declare class MetaService {
    loader: MetaLoader;
    private readonly router;
    private readonly activatedRoute;
    private readonly headService;
    private setTitleSubject;
    private readonly metaSettings;
    private readonly isMetaTagSet;
    private useRouteData;
    constructor(loader: MetaLoader, router: Router, activatedRoute: ActivatedRoute, headService: HeadService);
    onSetTitle(): Observable<string>;
    init(useRouteData?: boolean): void;
    refresh(): void;
    setTitle(title: string, override?: boolean): void;
    setTag(tag: string, value: string): void;
    private createMetaTag(name);
    private getOrCreateMetaTag(name);
    private callback(value);
    private getTitleWithPositioning(title, override);
    private updateTitle(title$);
    private updateLocales(currentLocale, availableLocales);
    private updateMetaTag(tag, value$);
    private updateMetaTags(currentUrl, metaSettings?);
    private traverseRoutes(route, url);
    private getMeta(snapshot);
}
